#!/usr/bin/env bash
# Friendly installer for Prowl — a local-AI, voice-first desktop agent for macOS.
#
# Every step is echoed and tolerant: optional pieces (GUI extras, the STT helper,
# the launcher shim, Ollama) only warn on failure so a partial setup still leaves
# you with a working `prowl` CLI. Nothing here downloads a model or touches the
# network beyond a small pip install of two pure front-end extras.
#
# IMPORTANT: macOS ships an old system python3 (often 3.9). Prowl needs 3.11+, so
# this script FINDS a suitable interpreter and pins its absolute path into the
# launcher — it never relies on whatever `python3` happens to be first on PATH.

set -euo pipefail

# --- 1. Resolve repo root relative to this script (scripts/ lives at top level).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

echo "==> Installing Prowl from ${REPO_ROOT}"
echo ""

# --- 2. Find a Python >= 3.11 and pin its ABSOLUTE path. --------------------
echo "==> Locating a Python 3.11+ interpreter"
PY=""
for cand in python3.14 python3.13 python3.12 python3.11 \
            /opt/homebrew/bin/python3 /usr/local/bin/python3 python3; do
    path="$(command -v "${cand}" 2>/dev/null || true)"
    [[ -z "${path}" ]] && continue
    if "${path}" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)' 2>/dev/null; then
        PY="$("${path}" -c 'import sys; print(sys.executable)')"
        break
    fi
done
if [[ -z "${PY}" ]]; then
    echo "error: no Python 3.11+ found. Install one (e.g. 'brew install python@3.13')" >&2
    echo "       then re-run this script." >&2
    exit 1
fi
echo "    Using ${PY}  ($("${PY}" --version))"
echo ""

# --- 3. Install the GUI extras (rumps, pynput). -----------------------------
# Small, pure front-end deps; the CLI core needs none of them. pyobjc is already
# present, so this is a quick, low-bandwidth install into the SAME interpreter.
echo "==> Installing GUI extras (menu-bar + hotkey)"
if "${PY}" -m pip install --user -r requirements.txt; then
    echo "    GUI extras installed."
else
    echo "warning: could not install GUI extras. The 'prowl' CLI still works;" >&2
    echo "         'prowl serve' (menu bar) and the hotkey may be unavailable." >&2
fi
echo ""

# --- 4. Build the on-device STT helper (best-effort). -----------------------
echo "==> Building the speech-to-text helper (prowl-listen)"
if bash scripts/build_stt.sh; then
    echo "    STT helper built."
else
    echo "warning: STT helper build failed. Voice input ('prowl listen') may not" >&2
    echo "         work until you run scripts/build_stt.sh successfully." >&2
fi
echo ""

# --- 5. Install a 'prowl' launcher with the pinned interpreter. -------------
# The shim runs the module with the repo on PYTHONPATH using the ABSOLUTE python
# path found above, so it keeps working even if PATH changes (e.g. after a
# reboot puts the system 3.9 first).
echo "==> Setting up a 'prowl' launcher"
LAUNCHER_INSTALLED=0
for TARGET_DIR in /usr/local/bin "${HOME}/bin"; do
    if [[ -d "${TARGET_DIR}" && -w "${TARGET_DIR}" ]]; then
        SHIM="${TARGET_DIR}/prowl"
        if cat > "${SHIM}" <<SHIM_EOF
#!/usr/bin/env bash
# Prowl launcher shim (generated by scripts/install.sh).
exec env PYTHONPATH="${REPO_ROOT}" "${PY}" -m prowl "\$@"
SHIM_EOF
        then
            chmod +x "${SHIM}"
            echo "    Installed launcher: ${SHIM}"
            LAUNCHER_INSTALLED=1
            break
        else
            echo "warning: could not write launcher to ${SHIM}." >&2
        fi
    fi
done
if [[ "${LAUNCHER_INSTALLED}" -eq 0 ]]; then
    echo "    No writable launcher dir (/usr/local/bin or ~/bin). To run Prowl,"
    echo "    add this to your shell profile:"
    echo ""
    echo "        alias prowl='PYTHONPATH=\"${REPO_ROOT}\" \"${PY}\" -m prowl'"
    echo ""
    echo "    Or run it directly from the repo:"
    echo "        PYTHONPATH=\"${REPO_ROOT}\" \"${PY}\" -m prowl <command>"
fi
echo ""

# --- 6. Check Ollama + the fast model (never auto-pull — bandwidth). ---------
echo "==> Checking Ollama and the local model (llama3.2:3b)"
if command -v ollama >/dev/null 2>&1; then
    echo "    Found ollama: $(command -v ollama)"
    if ollama list 2>/dev/null | grep -q "llama3.2:3b"; then
        echo "    Model llama3.2:3b is present."
    else
        echo "    Model llama3.2:3b is NOT installed. Pull it when you have"
        echo "    bandwidth (~2 GB, one-time):"
        echo ""
        echo "        ollama pull llama3.2:3b"
    fi
else
    echo "    ollama not found. Install it from https://ollama.com, then run:"
    echo ""
    echo "        ollama pull llama3.2:3b"
fi
echo ""

# --- 7. Run the environment check and print next steps. ---------------------
echo "==> Running 'prowl doctor'"
if ! PYTHONPATH="${REPO_ROOT}" "${PY}" -m prowl doctor; then
    echo "warning: doctor reported problems (see above). Prowl may still run;" >&2
    echo "         address any missing pieces before relying on it." >&2
fi
echo ""

echo "==> Prowl is set up. Next steps:"
echo "      prowl serve            start the always-on menu-bar app"
echo "      prowl listen           capture one voice turn and act on it"
echo "      prowl \"what's my ip\"   one-shot text command"
echo ""
echo "    Global hotkey (while 'prowl serve' is running): Cmd+Shift+Space."
