#!/usr/bin/env bash
# Friendly installer for Prowl — a local-AI, voice-first desktop agent for macOS.
#
# Every step is echoed and tolerant: optional pieces (GUI extras, the STT helper,
# the launcher shim, Ollama) only warn on failure so a partial setup still leaves
# you with a working `python3 -m prowl` CLI. Nothing here downloads a model or
# touches the network beyond the pip install of two small pure-front-end extras.

set -euo pipefail

# --- 1. Resolve repo root relative to this script (scripts/ lives at top level).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

echo "==> Installing Prowl from ${REPO_ROOT}"
echo ""

# --- 2. Check python3 (>=3.11) and print its version. -----------------------
echo "==> Checking python3 (>=3.11)"
if ! command -v python3 >/dev/null 2>&1; then
    echo "error: python3 not found on PATH. Install Python 3.11+ first." >&2
    exit 1
fi
echo "    $(python3 --version)"
if ! python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)'; then
    echo "error: Prowl needs Python 3.11 or newer. Please upgrade python3." >&2
    exit 1
fi
echo ""

# --- 3. Install the GUI extras (rumps, pynput). -----------------------------
# Small, pure front-end deps; the CLI core needs none of them. pyobjc is already
# present on this Mac, so this is a quick, low-bandwidth install.
echo "==> Installing GUI extras (menu-bar + hotkey)"
if python3 -m pip install --user -r requirements.txt; then
    echo "    GUI extras installed."
else
    echo "warning: could not install GUI extras. The 'prowl' CLI still works;" >&2
    echo "         'prowl serve' (menu bar) and the hotkey may be unavailable." >&2
fi
echo ""

# --- 4. Build the on-device STT helper (best-effort). -----------------------
echo "==> Building the speech-to-text helper (prowl-listen)"
if bash scripts/build_stt.sh; then
    echo "    STT helper built."
else
    echo "warning: STT helper build failed. Voice input ('prowl listen') may not" >&2
    echo "         work until you run scripts/build_stt.sh successfully." >&2
fi
echo ""

# --- 5. Offer to symlink a 'prowl' launcher. --------------------------------
# The shim just runs the module with the repo on PYTHONPATH, so it keeps working
# without a full package install. We only write it where the target is writable.
echo "==> Setting up a 'prowl' launcher"
LAUNCHER_INSTALLED=0
for TARGET_DIR in /usr/local/bin "${HOME}/bin"; do
    if [[ -d "${TARGET_DIR}" && -w "${TARGET_DIR}" ]]; then
        SHIM="${TARGET_DIR}/prowl"
        if cat > "${SHIM}" <<SHIM_EOF
#!/usr/bin/env bash
# Prowl launcher shim (generated by scripts/install.sh).
exec env PYTHONPATH="${REPO_ROOT}" python3 -m prowl "\$@"
SHIM_EOF
        then
            chmod +x "${SHIM}"
            echo "    Installed launcher: ${SHIM}"
            LAUNCHER_INSTALLED=1
            break
        else
            echo "warning: could not write launcher to ${SHIM}." >&2
        fi
    fi
done
if [[ "${LAUNCHER_INSTALLED}" -eq 0 ]]; then
    echo "    No writable launcher dir (/usr/local/bin or ~/bin). To run Prowl,"
    echo "    add this to your shell profile and use 'prowl' from anywhere:"
    echo ""
    echo "        export PYTHONPATH=\"${REPO_ROOT}\""
    echo "        alias prowl='python3 -m prowl'"
    echo ""
    echo "    Or just run it directly from the repo:"
    echo "        PYTHONPATH=\"${REPO_ROOT}\" python3 -m prowl <command>"
fi
echo ""

# --- 6. Check Ollama + the fast model (never auto-pull — bandwidth). ---------
echo "==> Checking Ollama and the local model (llama3.2:3b)"
if command -v ollama >/dev/null 2>&1; then
    echo "    Found ollama: $(command -v ollama)"
    if ollama list 2>/dev/null | grep -q "llama3.2:3b"; then
        echo "    Model llama3.2:3b is present."
    else
        echo "    Model llama3.2:3b is NOT installed. Pull it when you have"
        echo "    bandwidth (~2 GB, one-time):"
        echo ""
        echo "        ollama pull llama3.2:3b"
    fi
else
    echo "    ollama not found. Install it from https://ollama.com, then run:"
    echo ""
    echo "        ollama pull llama3.2:3b"
fi
echo ""

# --- 7. Run the environment check and print next steps. ---------------------
echo "==> Running 'prowl doctor'"
if ! PYTHONPATH="${REPO_ROOT}" python3 -m prowl doctor; then
    echo "warning: doctor reported problems (see above). Prowl may still run;" >&2
    echo "         address any missing pieces before relying on it." >&2
fi
echo ""

echo "==> Prowl is set up. Next steps:"
echo "      prowl serve            start the always-on menu-bar app"
echo "      prowl listen           capture one voice turn and act on it"
echo "      prowl \"what's my ip\"   one-shot text command"
echo ""
echo "    Global hotkey (while 'prowl serve' is running): Cmd+Shift+Space."
